In [1]:
import numpy as np 
l1=[1,2,3]
ar= np.array(l1)
ar

array([1, 2, 3])

In [2]:
ar2=np.array([[1,2,3],[2,3,5],[1,1,1]])
ar2

array([[1, 2, 3],
       [2, 3, 5],
       [1, 1, 1]])

In [3]:
ar.shape

(3,)

In [4]:
ar2.shape

(3, 3)

In [5]:
ar.dtype

dtype('int32')

In [6]:
ar2.dtype

dtype('int32')

In [7]:

np.zeros(3)


array([ 0.,  0.,  0.])

In [8]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [9]:
np.empty(3)

array([ 0.,  0.,  0.])

In [10]:
np.empty(3)
np.empty((4,2))

array([[  0.00000000e+000,   3.69561103e-321],
       [  2.47032823e-323,   5.25656458e-312],
       [  0.00000000e+000,   2.47032823e-323],
       [  5.25649099e-312,   0.00000000e+000]])

In [11]:
ar/2

array([ 0.5,  1. ,  1.5])

In [12]:
ar3=np.arange(3,6)
ar3

array([3, 4, 5])

In [13]:
ar3[2]

5

In [14]:
ar3[0:2]

array([3, 4])

In [15]:
ar3[0]=10
ar3

array([10,  4,  5])

In [16]:
ar3=np.arange(3,6)
ar3

array([3, 4, 5])

In [17]:
parar=ar3[1:3]
parar

array([4, 5])

In [18]:
parar[:]=99
parar

array([99, 99])

we note that the change happen in the sub array also happen in main array

In [19]:
ar3

array([ 3, 99, 99])

In [20]:
ar4=ar3.copy()
ar4

array([ 3, 99, 99])

In [21]:
ar2

array([[1, 2, 3],
       [2, 3, 5],
       [1, 1, 1]])

In [22]:
ar2[1][2]

5

In [23]:
ar2[0,2]

3

In [24]:
ar2[:2,1:]

array([[2, 3],
       [3, 5]])

In [25]:
aray=np.zeros([10,10])
aray

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [26]:
arshape=aray.shape[1]
arshape


10

In [27]:
for i in range(arshape):
    aray[i]=i
   
aray
     

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [28]:
aray[[2,5,6,8,9]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [29]:
aray

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [30]:
np.eye(5)


array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

لاحظ في الكود السابق ان ال1 على شكل قطر للمصفوفة 

In [31]:
5/2

2.5

In [32]:
aaaa=np.array([[1,2,5],[7,9,8]])

In [33]:
aaaa*aaaa

array([[ 1,  4, 25],
       [49, 81, 64]])

In [34]:
aaaa*2

array([[ 2,  4, 10],
       [14, 18, 16]])

In [36]:
aaaa**3

array([[  1,   8, 125],
       [343, 729, 512]], dtype=int32)

In [38]:
aaaa[1][0]

7